import home from '/public/Images/home.webp';
import home2 from '/public/Images/home2.webp';
import about from '/public/Images/about.webp';
import about2 from '/public/Images/lewis.webp';
import about3 from '/public/Images/sport.webp';
import arrivals from '/public/Images/arrivals.gif';
import asap from '/public/Images/asap.webp';
import asap2 from '/public/Images/asap2.webp';
import burna from '/public/Images/burna.webp';
import odumodu from '/public/Images/odumodu.webp';
import emblem from '/public/Images/emblem.webp';
import favicon from '/public/Images/favicon.webp';
import logo from '/public/Images/logo.webp';
import gta from '/public/Images/gta.webp';
import lewis from '/public/Images/lewis.webp';
import sport from '/public/Images/sport.webp';
import logo_black from '/public/Images/logo-black.webp';
import logo_blue from '/public/Images/logo-blue.webp';
import logo_white from '/public/Images/logo-white.webp';
import orange from '/public/Images/orange.webp';
import orange2 from '/public/Images/orange2.webp';
import plain from '/public/Images/plain.webp';
import plain2 from '/public/Images/plain2.webp';
import yellow from '/public/Images/yellow.webp';
import collectoion1 from '/public/Images/collection1.png';
import collectoion2 from '/public/Images/collection2.png';
import collectoion3 from '/public/Images/collection3.png';
import collectoion4 from '/public/Images/collection4.png';
import download  from '@/public/Images/download.png';


export const homeImage = home;
export const aboutImage = about;
export const aboutImage2 = about2;
export const aboutImage3 = about3;
export const arrivalsGif = arrivals;
export const asapImage = asap;
export const asapImage2 = asap2;
export const burnaImage = burna;
export const odumoduImage = odumodu;
export const emblemImage = emblem;
export const faviconImage = favicon;
export const logoImage = logo;
export const gtaImage = gta;
export const lewisImage = lewis;
export const sportImage = sport;
export const homeImage2 = home2;
export const logoBlackImage = logo_black;
export const logoBlueImage = logo_blue;
export const logoWhiteImage = logo_white;
export const orangeImage = orange;
export const orange2Image = orange2;
export const plainImage = plain;
export const plain2Image = plain2;
export const yellowImage = yellow;
export const collection1Image = collectoion1;
export const collection2Image = collectoion2;
export const collection3Image = collectoion3;
export const collection4Image = collectoion4;
export const downloadImage = download;
